general:
  result path: ./results/
  file types: FRA5095
  loss model: leastsq
  error evaluation: absolute
  upper frequency: 1.0e+30
  lower frequency: 0
params:
  - name: "Rs"
    min: 0
    initial: 1
    max: 100
  - name: "Rp"
    min: 5000
    initial: 75000
    max: 80000
  - name: "Tcpe"
    min: 0
    initial: 1.76e-9
    max: 2.0e-8
  - name: "p"
    min: 0
    initial: 0.97
    max: 1