general:
  result path: ./results
  file types: FRA5095
fitting:
  loss model: leastsq
  error evaluation: absolute
  upper frequency: 1.0e+30
  lower frequency: 0
params:
  - name: "Rs"
    min: 0
    initial: 1
    max: 1.0e+6
    unit: Ω
  - name: "Ls"
    min: 0
    initial: 1.0e-6
    max: 1
    unit: H
  - name: "Rp"
    min: 0
    initial: 75000
    max: 1.0e+6
    unit: Ω
  - name: "Tcpe"
    min: 0
    initial: 1.70e-9
    max: 1
    unit: Fs^(p-1)
  - name: "p"
    min: 0
    initial: 0.97
    max: 1
func:
  defs:
    - CPE = 1
  expr: Rs + 1j*2*3.14159265359*f*Ls + 1/(1/Rp + ((1j*2*3.14159265359*f)**p)*Tcpe)
